CREATE DATABASE QLYGIAOVU

USE QLYGIAOVU

CREATE TABLE KHOA(
MAKHOA varchar(4) NOT NULL CONSTRAINT PK_KHOA PRIMARY KEY,
TENKHOA varchar(40),
NGTLAP smalldatetime,
TRGKHOA char(4),
)

CREATE TABLE MONHOC(
MAMH varchar(10) NOT NULL CONSTRAINT PK_MH PRIMARY KEY,
TENMH varchar(40),
TCLT tinyint,
TCTH tinyint,
MAKHOA varchar(4) CONSTRAINT FK_MH_KH FOREIGN KEY REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DIEUKIEN(
MAMH varchar(10) CONSTRAINT FK_MMH FOREIGN KEY REFERENCES MONHOC(MAMH),
MAMH_TRUOC varchar(10) CONSTRAINT FK_MH_TRUOC FOREIGN KEY REFERENCES MONHOC(MAMH),
CONSTRAINT PK_DK PRIMARY KEY (MAMH,MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN(
MAGV char(4) NOT NULL CONSTRAINT PK_GV PRIMARY KEY,
HOTEN varchar(40),
HOCVI varchar(10),
HOCHAM varchar(10),
GIOITINH varchar(3),
NGSINH smalldatetime,
NGVL smalldatetime,
HESO numeric(4,2),
MUCLUONG money,
MAKHOA varchar(4) CONSTRAINT FK_GV_KH FOREIGN KEY REFERENCES KHOA(MAKHOA)
)

CREATE TABLE LOP(
MALOP char(3) NOT NULL CONSTRAINT PK_LOP PRIMARY KEY,
TENLOP varchar(40),
TRGLOP char(5),
SISO tinyint,
MAGVCN char(4) CONSTRAINT FK_GV_LOP FOREIGN KEY REFERENCES GIAOVIEN(MAGV)
)

CREATE TABLE HOCVIEN(
MAHV char(5) NOT NULL CONSTRAINT PK_HV PRIMARY KEY,
HO varchar(40),
TEN varchar(10),
NGSINH smalldatetime,
GIOITINH varchar(3),
NOISINH varchar(40),
MALOP char(3) CONSTRAINT FK_HV_L FOREIGN KEY REFERENCES LOP(MALOP)
)

CREATE TABLE GIANGDAY(
MALOP char(3) CONSTRAINT FK_GD_L FOREIGN KEY REFERENCES LOP(MALOP),
MAMH varchar(10) CONSTRAINT FK_GD_MH FOREIGN KEY REFERENCES MONHOC(MAMH),
MAGV char(4) CONSTRAINT FK_GV_GD FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
HOCKY tinyint,
NAM smallint,
TUNGAY smalldatetime,
DENNGAY smalldatetime,
CONSTRAINT PK_GD PRIMARY KEY (MALOP,MAMH)
)

CREATE TABLE KETQUATHI(
MAHV char(5) CONSTRAINT FK_KQ_HV FOREIGN KEY REFERENCES HOCVIEN(MAHV),
MAMH varchar(10) CONSTRAINT FK_KQ_MH FOREIGN KEY REFERENCES MONHOC(MAMH),
LANTHI tinyint,
NGTHI smalldatetime,
DIEM numeric(4,2),
KQUA varchar(10),
CONSTRAINT PK_KQ PRIMARY KEY (MAHV,MAMH,LANTHI)
)

ALTER TABLE KHOA
ADD CONSTRAINT FK_TRGK FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)


/*3. Thuoc tinh GIOITINH chi có gia tri la “Nam” hoac “Nu”.*/
ALTER TABLE GIAOVIEN
ADD CONSTRAINT GT CHECK (GIOITINH = 'Nam' OR GIOITINH = 'Nu')
ALTER TABLE HOCVIEN
ADD CONSTRAINT GT_HV CHECK (GIOITINH = 'Nam' OR GIOITINH = 'Nu')

/*4. Diem so cua mot lan thi co gia tri tu 0 den 10 va can luu den 2 so le*/
ALTER TABLE KETQUATHI
ADD CONSTRAINT DIEM_C CHECK (DIEM BETWEEN 0 AND 10)

/*5. Ket qua thi la “Dat” neu diem tu 5 den 10 va “Khong dat” neu diem nho hon 5*/
ALTER TABLE KETQUATHI
ADD CONSTRAINT KQT CHECK (KQUA = IIF((DIEM BETWEEN 5 AND 10), 'Dat', 'Khong dat'))

/*6. Hoc vien thi mot mon toi da 3 lAn*/
ALTER TABLE KETQUATHI
ADD CONSTRAINT LAN_CHECK CHECK (LANTHI >= 1 AND LANTHI <= 3)

/*7. Hoc ky chi co gia tri tu 1 den 3*/
ALTER TABLE GIANGDAY
ADD CONSTRAINT HK_CHECK CHECK (HOCKY BETWEEN 1 AND 3)

/*8. Hoc vi cua giao vien chi co the la “CN”, “KS”, “Ths”, ”TS”, ”PTS”*/
ALTER TABLE GIAOVIEN
ADD CONSTRAINT HOCVI_CHECK CHECK (HOCVI in ('CN', 'KS', 'Ths', 'TS', 'PTS'))





