CREATE DATABASE BAITHI
USE BAITHI
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(100),
	QUOCGIA VARCHAR(50),
	LOAINCC VARCHAR(50)
)

CREATE TABLE DUOCPHAM
(
	MADP VARCHAR(4) PRIMARY KEY,
	TENDP VARCHAR(100),
	LOAIDP VARCHAR(50),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP
(
	SOPN VARCHAR(5) PRIMARY KEY,
	NGNHAP SMALLDATETIME,
	MANCC VARCHAR(5),
	LOAINHAP VARCHAR(50)
)

CREATE TABLE CTPN 
(
	SOPN VARCHAR(5),
	MADP VARCHAR(4),
	SOLUONG INT,
	PRIMARY KEY (SOPN, MADP)
)

SET DATEFORMAT DMY

INSERT INTO NHACUNGCAP VALUES('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen'),
							 ('NCC02', 'J. B. Pharmaeuticals', 'India', 'Vang lai'),
							 ('NCC03', 'Sapharco', 'Singapore', 'Vang lai')

INSERT INTO DUOCPHAM VALUES('DP01', 'Thuoc ho PH', 'Siro', 120000),
						   ('DP02', 'Zecuf Herbal CounchRemedy', 'Vien nen', 200000),
						   ('DP03', 'Cotrim', 'Vien nen', 80000)

INSERT INTO PHIEUNHAP VALUES('00001', '22/11/2017', 'NCC01', 'Noi dia'),
						    ('00002', '04/12/2017', 'NCC03', 'Nhap khau'),
						    ('00003', '10/12/2017', 'NCC02', 'Nhap khau')

INSERT INTO CTPN VALUES('00001', 'DP01', 100),
					   ('00001', 'DP02', 200),
					   ('00003', 'DP03', 543)

ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CTPN_PN FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CTPN_DP FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)

-- 3.
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CK_SIRO CHECK (LOAIDP != 'Siro' OR GIA > 100000)

--4.
GO
CREATE TRIGGER TRG_PN ON PHIEUNHAP
AFTER UPDATE, INSERT
AS
BEGIN
	IF EXISTS(SELECT *
			  FROM inserted i, NHACUNGCAP NCC
			  WHERE i.MANCC = NCC.MANCC
			  AND NCC.QUOCGIA != 'Viet Nam'
			  AND i.LOAINHAP != 'Nhap khau')
	BEGIN
		RAISERROR('LOI', 16, 1);
		ROLLBACK TRAN
	END
END

GO
CREATE TRIGGER TRG_NCC ON NHACUNGCAP
AFTER UPDATE
AS
BEGIN
	IF EXISTS(SELECT * 
			  FROM inserted i, PHIEUNHAP PN
			  WHERE i.MANCC = PN.MANCC
			  AND i.QUOCGIA != 'Viet Nam'
			  AND PN.LOAINHAP != 'Nhap khau')
	BEGIN
		RAISERROR('LOI1', 16, 1);
		ROLLBACK TRAN
	END
END
--5.Tìm tất cả các phiếu nhập có ngày nhập trong tháng 12 năm 2017.sắp xếp kết quả tăng dần
--theo ngày nhập (1đ).

SELECT SOPN
FROM PHIEUNHAP
WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2017
ORDER BY NGNHAP ASC

--6.Tìm dược phẩm được nhập số lượng nhiều nhất trong năm 2017 (1đ).

SELECT MADP
FROM CTPN
INNER JOIN PHIEUNHAP PN ON CTPN.SOPN = PN.SOPN
WHERE YEAR(NGNHAP) = 2017 
GROUP BY MADP
HAVING SUM(SOLUONG) >= ALL (SELECT SUM(SOLUONG)
					FROM CTPN
					INNER JOIN PHIEUNHAP PN1 ON CTPN.SOPN = PN1.SOPN
					WHERE YEAR(NGNHAP) = 2017
					GROUP BY MADP)

--7.Tìm dược phẩm chỉ có nhà cung cấp thường xuyên (LOAINCC là Thuong xuyen) cung cấp,
--nhà cung cấp vãng lai (LOAINCC là Vang lai) không cung cấp

SELECT MADP
FROM CTPN
INNER JOIN PHIEUNHAP PN ON CTPN.SOPN = PN.SOPN
INNER JOIN NHACUNGCAP NCC ON PN.MANCC = NCC.MANCC
WHERE LOAINCC = 'Thuong xuyen'
AND MADP NOT IN (SELECT MADP
				 FROM CTPN
				 INNER JOIN PHIEUNHAP PN1 ON CTPN.SOPN = PN1.SOPN
				 INNER JOIN NHACUNGCAP NCC1 ON PN1.MANCC = NCC1.MANCC
			     WHERE LOAINCC = 'Vang lai')

--8. Tìm nhà cung cấp đã từng cung cấp tất cả những dược phẩm có giá trên 100.000đ trong năm
--2017 (1đ)

SELECT NCC.MANCC, TENNCC
FROM NHACUNGCAP NCC
WHERE NOT EXISTS (SELECT *
				 FROM DUOCPHAM DP
				 INNER JOIN CTPN ON DP.MADP = CTPN.MADP
				 WHERE GIA > 100000
				 AND NOT EXISTS (SELECT *
								   FROM PHIEUNHAP PN
								   WHERE PN.SOPN = CTPN.SOPN
								   AND PN.MANCC = NCC.MANCC
								   AND YEAR(NGNHAP) = 2017))
